/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;

/**
 *
 * @author LU
 */
public class TablesWindow extends javax.swing.JFrame {

    private ViewController controller; 
    
    /**
     * Creates new form TableWindow
     */
    public TablesWindow(ViewController c) {
        initComponents();
        controller = c;
        this.setVisible(true);
        this.jListTables.setModel(new DefaultListModel());
    }
    
    public void setCreateError(String err){
        this.jLabelCreateError.setText(err);
    }
    
    public void setTableListError(String err){
        this.jLabelJoinError.setText(err);
    }
    
    public void addToTableList(String name){
        ( (DefaultListModel) this.jListTables.getModel()).addElement(name);
    }
    
    public void clearTableList(){
        ( (DefaultListModel) this.jListTables.getModel()).clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelJoinTitle = new javax.swing.JLabel();
        jLabelJoinDesc = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTables = new javax.swing.JList<>();
        jButtonJoin = new javax.swing.JButton();
        jLabelCreateTitle = new javax.swing.JLabel();
        jLabelJoinError = new javax.swing.JLabel();
        jLabelCreateDesc = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabelTableName = new javax.swing.JLabel();
        jTextTableName = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jLabelCreateError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catch the Thief!");

        jLabelJoinTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelJoinTitle.setText("Dostępne rozgrywki");

        jLabelJoinDesc.setText("<html><div style='text-align: justify;'>Aby dołączyć do istniejącej rozgrywki, wybierz  stół z dostępnej listy i kliknij Dołącz do rozgrywki. Lista stołów nie jest odświeżana automatycznie, dlatego aby pobrać aktualną listę, kliknij przycisk Odśwież listę.</div></html>");

        jButtonUpdate.setText("Odśwież listę");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListTables);

        jButtonJoin.setText("Dołącz do rozgrywki");
        jButtonJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinActionPerformed(evt);
            }
        });

        jLabelCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCreateTitle.setText("Tworzenie nowej rozgrywki");

        jLabelJoinError.setForeground(new java.awt.Color(204, 0, 0));

        jLabelCreateDesc.setText("<html><div style='text-align: justify;'>Aby utworzyć nowy stół do gry, wpisz jego nazwę, a następnie kliknij Utwórz stół. Nazwa stołu może zawierać wyłacznie litery i cyfry oraz musi być unikatowa.</div></html>");

        jLabelTableName.setText("Nazwa stołu:");

        jTextTableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTableNameActionPerformed(evt);
            }
        });

        jButtonCreate.setText("Utwórz rozgrywkę");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabelCreateError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCreateError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJoinError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJoinDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonJoin, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabelCreateDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJoinTitle)
                                    .addComponent(jLabelCreateTitle))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTableName))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJoinTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJoinDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonJoin)))
                .addGap(14, 14, 14)
                .addComponent(jLabelJoinError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCreateTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCreateDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTableName)
                    .addComponent(jTextTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCreateError, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        this.controller.actionUpdateTableList();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinActionPerformed
        String name = this.jListTables.getSelectedValue();
        this.controller.actionJoinTable(name);
    }//GEN-LAST:event_jButtonJoinActionPerformed

    private void jTextTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTableNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTableNameActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        String name = this.jTextTableName.getText();
        this.controller.actionCreateTable(name);
    }//GEN-LAST:event_jButtonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonJoin;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelCreateDesc;
    private javax.swing.JLabel jLabelCreateError;
    private javax.swing.JLabel jLabelCreateTitle;
    private javax.swing.JLabel jLabelJoinDesc;
    private javax.swing.JLabel jLabelJoinError;
    private javax.swing.JLabel jLabelJoinTitle;
    private javax.swing.JLabel jLabelTableName;
    private javax.swing.JList<String> jListTables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextField jTextTableName;
    // End of variables declaration//GEN-END:variables
}
